version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dandevko:dandevko@db/senior_project
    expose:
      - "8080"
    networks:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: senior_project
      POSTGRES_USER: dandevko
      POSTGRES_PASSWORD: dandevko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    depends_on:
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
