version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
