version: "3.8"
services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://dandevko:dandevko@db/senior_project
    expose:
      - "8080"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    ports:
      - "8080:8080"

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: senior_project
      POSTGRES_USER: dandevko
      POSTGRES_PASSWORD: dandevko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dandevko -d senior_project"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
