version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://dandevko:dandevko@db/senior_project
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: senior_project
      POSTGRES_USER: dandevko
      POSTGRES_PASSWORD: dandevko
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
